BigStoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace BigStoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _repositoryManager;

        public CategoryController(IRepositoryManager repositoryManager)
        {
            _repositoryManager = repositoryManager;
        }

        public IActionResult Index()
        {
            var model = _repositoryManager.Category.FindAll(false);
            return View(model);
        }
    }
}

BigStoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace BigStoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _services;
        private readonly Cart _cart;

        public OrderController(IServiceManager services, Cart cart)
        {
            _services = services;
            _cart = cart;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Checkout() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order) 
        {
            if (_cart.Lines.Count() == 0) 
                ModelState.AddModelError("","Sorry, cart is empty.");
            if(ModelState.IsValid) 
            {
                order.Lines = _cart.Lines.ToArray();
                _services.OrderService.SaveOrder(order);
                _cart.ClearCart();
                return RedirectToPage("/Complete", new {orderId = order.OrderId});
            }

            return View();
        }
    }
}

BigStoreApp/Controllers/ProductController.cs
using BigStoreApp.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;

namespace BigStoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public ProductController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var products = _serviceManager.ProductService.GetAllProductsWithDetails(p).ToList();
            
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItem = _serviceManager.ProductService.GetAllProducts(false).Count()
            };

            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get(int id)
        {
            var product = _serviceManager.ProductService.GetProductWithId(id, false);
            return View(product);
        }
    }
}

BigStoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> BigStoreApp/Admin - @ViewData["Title"] </title>
    <link rel="stylesheet" asp-append-version="true" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-append-version="true" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" asp-append-version="true" href="~/BigStoreApp.styles.css" asp-append-version="true" />                              
    <link rel="stylesheet" asp-append-version="true" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">BigStoreApp-ADMIN</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" area-current="page" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" area-current="page" asp-area="Admin" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" area-current="page" asp-area="Admin" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" area-current="page" asp-area="Admin" asp-controller="Order" asp-action="Index">ORDERS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" area-current="page" asp-area="Admin" asp-controller="Role" asp-action="Index">ROLES</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" area-current="page" asp-area="Admin" asp-controller="User" asp-action="Index">USERS</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav text-white">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">
                                <i class="fa fa-solid fa-search"></i> WEB</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Logout" asp-route-returnUrl="@Url.ActionContext.HttpContext.Request.Path">
                                <i class="fa-solid fa-right-from-bracket"></i> Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <div>
            <partial name="_Notification" />
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="pt-5">
        <partial name="_Footer"></partial>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>