BigStoreApp/Areas/Admin/Controllers/ProductController.cs
using BigStoreApp.Models;
using Entities.Dtos;
using Entities.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Concretes;
using Services.Contracts;

namespace BigStoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IServiceManager _service;

        public ProductController(IServiceManager service)
        {
            _service = service;
        }

        private SelectList GetCategories(int? selectedCatId)
        {
            if (selectedCatId != 0)
                return new SelectList(_service.CategoryService.GetAllCategories(false), "CategoryId", "Name", selectedCatId);

            return new SelectList(_service.CategoryService.GetAllCategories(false), "CategoryId",
                "Name",
                "1");
        }

        public IActionResult Index([FromQuery] ProductRequestParameters p)
        {
            ViewData["Title"] = "Products";
            var products = _service.ProductService.GetAllProductsWithDetails(p).ToList();

            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItem = _service.ProductService.GetAllProducts(false).Count()
            };

            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        //CREATE
        public IActionResult CreateProduct()
        {
            ViewBag.Categories = GetCategories(0);
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateProduct([FromForm] ProductDTOInsertion productDTOInsertion, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                //file operation
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "_photos", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                productDTOInsertion.ImageURL = string.Concat("_photos/", file.FileName);
                _service.ProductService.CreateProduct(productDTOInsertion);

                TempData["success"] = $"{productDTOInsertion.Name} has been created at {DateTime.Now.ToShortDateString()}";

                return RedirectToAction("Index");
            }
            return View();
        }

        //UPDATE
        public IActionResult UpdateProduct([FromRoute(Name = "Id")] int id)
        {
            var model = _service.ProductService.GetProductWithIdForUpdate(id, false);

            if (ModelState.IsValid && model != null)
            {
                ViewData["Title"] = model.Name;
                ViewBag.Categories = GetCategories(model.CategoryId);
                //string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", model.ImageURL);
                return View(model);
            }
            return View();

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateProduct([FromForm] ProductDTOUpdate productDTOUpdate, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                //file operation
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "_photos", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }

                productDTOUpdate.ImageURL = string.Concat("_photos/", file.FileName);
                _service.ProductService.UpdateProduct(productDTOUpdate);

                TempData["info"] = $"Product updated success. ({DateTime.Now.ToShortDateString()})";
                return RedirectToAction("Index");
            }
            return View();
        }

        //DELETE
        public IActionResult DeleteProduct([FromRoute(Name = "Id")] int id)
        {
            if (_service.ProductService.DeleteProduct(id))
            {
                TempData["info"] = "Product deleted successfully.";
                return RedirectToAction("Index");
            }

            ViewBag.ErrorMessage = "Product delete process failed, try again.\"";
            return View("Index");
        }

        [HttpPost]
        public IActionResult ToggleShowcase([FromForm] int id)
        {
            _service.ProductService.ToggleShowcase(id);
            return RedirectToAction("Index");
        }
    }
}

BigStoreApp/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace BigStoreApp.Components
{
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _services;

        public CategoriesMenuViewComponent(IServiceManager services)
        {
            _services = services;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _services.CategoryService.GetAllCategories(false);
            return View(categories);
        }
    }
}

BigStoreApp/Components/ProductFilterMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace BigStoreApp.Components
{
    public class ProductFilterMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

BigStoreApp/Controllers/ProductController.cs
using BigStoreApp.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;

namespace BigStoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public ProductController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var products = _serviceManager.ProductService.GetAllProductsWithDetails(p).ToList();
            
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItem = _serviceManager.ProductService.GetAllProducts(false).Count()
            };

            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get(int id)
        {
            var product = _serviceManager.ProductService.GetProductWithId(id, false);
            return View(product);
        }
    }
}

BigStoreApp/Areas/Admin/Views/Product/CreateProduct.cshtml
@{
    ViewData["Title"] = "CreateProduct";
}
@model ProductDTOInsertion

<div class="text-center">
    <div class="display-6"> CREATE </div>
</div>

<form method="post" asp-action="CreateProduct" enctype="multipart/form-data">
    <div class="text-danger" asp-validation-summary="All"></div>
    
    <div class="form-group my-3">
        <label asp-for="CategoryId"></label>
        <select class="form-control" asp-items="@ViewBag.Categories" asp-for="CategoryId"> </select>
    </div>

    <div class="form-group my-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" placeholder="Please fill it."/>
    </div>
    <div class="form-group my-3">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control" placeholder="Please fill it." />
    </div>
    <div class="form-group my-3">
        <label asp-for="Summary"></label>
        <input asp-for="Summary" class="form-control" placeholder="Summary" />
    </div>
    <div class="form-group my-3">
        <label asp-for="ImageURL"></label>
        <input name="file" type="file" class="form-control" placeholder="Select Path" accept="image/*" />
    </div>

    <div class="form-group my-3">
        <div>
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-save"></i> Save
            </button>
            <a asp-action="Index" class="btn btn-outline-primary">
                <i class="fa fa-list"> </i>
                Products
            </a>
        </div>
    </div>
</form>

BigStoreApp/Areas/Admin/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model ProductListViewModel

<div class="text-center">
    <div class="display-6">Products</div>

    <div class="d-flex justify-content-end">
        <a class="btn btn-outline-success" asp-action="CreateProduct">
            <span>&#43;</span> CREATE
        </a>
    </div>
    <br />

    @if (ViewBag.ErrorMessage != null)
    {
        <div class="alert alert-danger">
            @ViewBag.ErrorMessage
        </div>
    }

    <div class="row">
        <div class="col-md-2 custom-style">
            @await Component.InvokeAsync("CategoriesMenu")
            @await Component.InvokeAsync("ProductFilterMenu")
            <br />
            <div products="" number="4"></div>
        </div>

        <div class="col-md-10">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Product Name</th>
                        <td>Showcase</td>
                        <th>Price</th>
                        <th>Product Image</th>
                        <th>Operations</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (Product item in Model.Products)
                    {
                        <tr>
                            <td>@item.ProductId</td>
                            <td>@item.Name</td>
                            <td>
                                <div class="form-check form-switch">
                                    <form asp-action="ToggleShowcase" method="post">
                                        <input type="hidden" name="Id" value="@item.ProductId" />
                                        <input type="checkbox" class="form-check-input mx-auto" name="Showcase"
                                               onchange="this.form.submit()" @(item.Showcase ? "checked" : "") />
                                    </form>
                                </div>
                            </td>
                            <td>@item.Price.ToString("c")</td>
                            <td>
                                <img src="@Url.Content("~/" + item.ImageUrl)" alt="@item?.Name" width="50">
                            </td>
                            <td>
                                <div class="btn-group">
                                    <a data-toggle="tooltip"
                                       data-placement="top"
                                       title="Edit"
                                       class="btn btn-warning" asp-action="UpdateProduct" asp-route-id="@item.ProductId">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                    <a data-toggle="tooltip"
                                       data-placement="top"
                                       title="Search"
                                       class="btn btn-info" target="_blank" asp-area="" asp-controller="Product" asp-action="Get" asp-route-id="@item.ProductId">
                                        <i class="fa fa-search"></i>
                                    </a>
                                    <a data-toggle="tooltip"
                                       data-placement="top"
                                       title="Delete"
                                       class="btn btn-danger" asp-action="DeleteProduct" asp-route-id="@item.ProductId">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div>
                <div page-model="@Model?.Pagination"
                     page-action="Index"
                     page-classes-enabled="true"
                     page-class="btn"
                     page-class-normal="btn-outline-dark"
                     page-classes-selected="btn-primary"
                     class="btn-group">
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <script type="text/javascript">
        $(document).ready(() => {
            $('[data-toggle = "tooltip"]').tooltip()
        });
    </script>
}

BigStoreApp/Areas/Admin/Views/Product/UpdateProduct.cshtml
@{
    ViewData["Title"] = "UpdateProduct";
}
@model ProductDTOUpdate

<div class="text-center">
    <div class="display-6"></div>
</div>

<div class="col-md-6">
    <form method="post" asp-action="UpdateProduct" enctype="multipart/form-data">
        <div class="text-danger" asp-validation-summary="All"></div>
        <input type="hidden" asp-for="ProductId" />

        <div class="form-group my-3">
            <label asp-for="CategoryId"> Category </label>
            <select class="form-control" asp-items="@ViewBag.Categories" asp-for="CategoryId">  </select>
        </div>

        <div class="form-group my-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="form-group my-3">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
        </div>
        <div class="form-group my-3">
            <label asp-for="Summary"></label>
            <input asp-for="Summary" class="form-control" placeholder="Summary" />
        </div>

        <!-- Resim gosterimi -->
        <label>Current Image</label>
        <div class="form-group" my-3>
            <img class="rounded shadow" width="200" alt="@Model?.Name" src="@Url.Content("~/" + @Model?.ImageURL)" />
        </div>

        <!-- Resim secimi -->
        <div class="form-group my-3">
            <input name="file" type="file" class="form-control" accept="image/*" required/>
        </div>

        <div class="form-group my-3">
            <input asp-for="Showcase" />
            <label> Show on showcase </label>
        </div>

        <!-- submit butonu -->
        <div class="form-group my-3">
            <div>
                <button class="btn btn-primary" type="submit">
                    <i class="fa fa-save"></i> Update
                </button>
                <a asp-action="Index" class="btn btn-outline-primary">
                    <i class="fa fa-list"> </i>
                    Products
                </a>
            </div>
        </div>

    </form>
</div>