BigStoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace BigStoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _services;
        private readonly Cart _cart;

        public OrderController(IServiceManager services, Cart cart)
        {
            _services = services;
            _cart = cart;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize]
        public IActionResult Checkout() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Checkout([FromForm] Order order) 
        {
            if (_cart.Lines.Count() == 0) 
                ModelState.AddModelError("","Sorry, cart is empty.");
            if(ModelState.IsValid) 
            {
                order.Lines = _cart.Lines.ToArray();
                _services.OrderService.SaveOrder(order);
                _cart.ClearCart();
                return RedirectToPage("/Complete", new {orderId = order.OrderId});
            }

            return View();
        }
    }
}

BigStoreApp/Pages/Cart.cshtml.cs
using BigStoreApp.Infrastructure.Extensions;
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Contracts;

namespace BigStoreApp.Pages
{
    public class CartModel : PageModel
    {
        private readonly IServiceManager _services;
        public Cart _Cart { get; set; } //IOC
        
        public CartModel(IServiceManager services, Cart _cartService)
        {
            _services = services;
            _Cart = _cartService;
        }

        public string ReturnURL { get; set; } = "/";

        //Biz kullaniciya ne donecegiz
        public void OnGet(string returnURL)
        {
            ReturnURL = returnURL ?? "/";
        }

        public IActionResult OnPost(int productId, String returnURL)
        {
            var product = _services.ProductService.GetProductWithId(productId, false);

            if (product is not null)
                _Cart.AddItem(product, 1);
            return RedirectToPage(new { returnURL = returnURL});
        }
        public IActionResult OnPostRemove(int id, String returnURL)
        {
            _Cart.RemoveLine(_Cart.Lines.First(cl => cl.Product.ProductId.Equals(id)).Product);
            return Page();
        }
    }
}

BigStoreApp/Pages/Complete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BigStoreApp.Pages
{
    public class CompleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BigStoreApp/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.ComponentModel.DataAnnotations;

namespace BigStoreApp.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

BigStoreApp/Pages/Cart.cshtml
@page "/cart"  
@model CartModel
@{
    ViewData["Title"] = "Cart";
}

<h2>@ViewData["Title"]</h2>

@if (Model._Cart.Lines.Any())
{
    <div class="text-center display 6"> CART </div>

    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>SubTotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model._Cart.Lines)
            {
                <tr>
                    <td>@line.Product.Name</td>
                    <td>@line.Quantity</td>
                    <td>@line.Product.Price.ToString("c")</td>
                    <td>@((line.Quantity * line.Product.Price).ToString("c2"))</td>
                    <td>
                        <form asp-page-handler="Remove" method="post">
                            <input type="hidden" name="id" value="@line.Product.ProductId" />
                            <input type="hidden" name="returnURL" value="@Model.ReturnURL" />
                            <button type="submit" class="btn btn-danger btn-sm">
                                <i class="fa fa-trash"></i> Remove</button>
                        </form>
                    </td>
                </tr>
            }
            <tr>
                <td colspan="3"></td>
                <td><strong>Total:</strong></td>
                <td>@Model._Cart.ComputeTotalValue().ToString("c")</td>
            </tr>
        </tbody>
    </table>

    <div class="text-center my-3">
        <div class="btn-group">
            <a class="btn btn-primary" href="@Model?.ReturnURL">Continue shopping</a>
            <a class="btn btn-primary mx-2" asp-action="Checkout" asp-controller="Order"> Checkout </a>
        </div>
    </div>
}
else
{
    <p>Your cart is empty.</p>
}

BigStoreApp/Pages/Complete.cshtml
@page
 
<div class="text-center">
    <h6 class="display-6"> Thanks </h6>
    <p> Thank for a placing order #@OrderId</p>
    <p> We'll ship your good as soon as possible.</p>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Return to Store</a> 
</div>

@functions
{
    [BindProperty(SupportsGet =true)]
    public string? OrderId { get; set; }
}

BigStoreApp/Pages/Contact.cshtml
@page "/getintouch"

<div class="text-center display-5"> CONTACT </div>
<div class="text-center border my-5">
    <div class="lead">
        <i class="fa fa-phone"> </i>
        <p> Bilgi Ve Destek Hattı </p>
        <i class="fa-solid fa-address-book"> </i>
        <p> Toronto/ON Kanada </p>
        <i class="fa-solid fa-envelope"> </i>
        <p> info@eaglestore.com</p>
    </div>
</div>