BigStoreApp/Components/CartSummaryViewComponent.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace BigStoreApp.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private readonly Cart _cart;

        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public string Invoke()
        {
            return _cart.Lines.Count().ToString();
        }
    }
}

BigStoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;
using StoreApp.Repositories;

namespace BigStoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        private readonly IServiceManager _services;

        public ProductSummaryViewComponent(IServiceManager services)
        {
            _services = services;
        }

        public string Invoke()
        {
            return _services.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

BigStoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace BigStoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _repositoryManager;

        public CategoryController(IRepositoryManager repositoryManager)
        {
            _repositoryManager = repositoryManager;
        }

        public IActionResult Index()
        {
            var model = _repositoryManager.Category.FindAll(false);
            return View(model);
        }
    }
}

BigStoreApp/Controllers/ProductController.cs
using BigStoreApp.Models;
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;
using Services.Contracts;

namespace BigStoreApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public ProductController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public IActionResult Index(ProductRequestParameters p)
        {
            var products = _serviceManager.ProductService.GetAllProductsWithDetails(p).ToList();
            
            var pagination = new Pagination()
            {
                CurrentPage = p.PageNumber,
                ItemsPerPage = p.PageSize,
                TotalItem = _serviceManager.ProductService.GetAllProducts(false).Count()
            };

            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }

        public IActionResult Get(int id)
        {
            var product = _serviceManager.ProductService.GetProductWithId(id, false);
            return View(product);
        }
    }
}

BigStoreApp/Views/Shared/ProductCard.cshtml
@{
    ViewData["Title"] = "ProductCard";
}
@model Product

<div class="col-sm-12 col-md-4 col-lg-3 my-3 d-flex align-items-stretch">
    <div class="card" style="width: 18rem;">
        
        <div class="card-header text-center">
            @Model.Name
        </div>

        <img src="@Url.Content("~/" + @Model.ImageUrl)" class="card-img-top" alt="@Model.Name">
        <div class="card-body">
            <div class="card-text">
                <div class="text-danger text-center lead p-2 rounded-2">
                    @Model.Price.ToString("C2")
                </div>
            </div>
            <p class="card-text">@Model.Summary</p>

            <div class="btn btn-group d-flex justify-content-center" style="display: flex; gap: 5px;">
                
                <a asp-controller="Product" asp-action="Get" asp-route-id="@Model.ProductId" class="btn btn-primary btn-sm"> <i class="fa fa-right-arrow"></i>
                    Details</a>

                <form id="@Model.ProductId" asp-page="/cart" method="post">
                    <input type="hidden" asp-for="ProductId"/>
                    <input type="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                    <button type="submit" class="btn btn-outline-primary">
                        <i class="fa fa-cart-plus"></i>
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

BigStoreApp/Views/Shared/_Footer.cshtml
<div class="bg-light border-top p-3">
    <div class="container">
        <div class="row">
            <!-- Logo and About Section -->
            <div class="col-md-2 text-md-start mb-3 mb-md-0">
                <div class="d-flex align-items-center">
                    <img src="/_Photos/logo.png" alt="Logo" class="footer-logo me-2">
                    <div>
                        <h5 class="text-warning mb-0">StoreApp</h5>
                        <p class="small mb-0">
                            Discover customazible site for you.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <div class="text-center text-muted my-3">
                    &copy; 2024 <br /> Store App Version 1.0
                </div>
                <div class="text-center">
                    <div class="btn-group">
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-facebook"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-twitter"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-linkedin"></i>
                        </a>
                        <a class="btn btn-secondary">
                            <i class="fa-brands fa-youtube"></i>
                        </a>
                    </div>
                </div>

            </div>
            <div class="col-md-2">
                <div products="" number="2"> </div>
            </div>
        </div>
        
    </div>
</div>

BigStoreApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Custom Store App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BigStoreApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm custom-navbar border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-secondary" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="fa-solid fa-store text-secondary">  </i>
                    BigStoreApp
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products(@await Component.InvokeAsync("ProductSummary"))</a>
                        </li>
                        <!--<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/Contact">CONTACT</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav text-dark">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cart" >
                                <i class="fa-solid fa-cart-shopping"></i> CART
                                (@await Component.InvokeAsync("CartSummary"))
                            </a>
                        </li>
                        
                        <partial name="_LoginMenu" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    
    <div class="container">
        <div>
            <partial name="_Notification" />
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="pt-5">
        @RenderSection("Footer",false)
        <partial name="_Footer"></partial>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

BigStoreApp/Views/Shared/_LoginMenu.cshtml
@using BigStoreApp.Infrastructure.Extensions;

<!--
    Authentication Middleware: app.UseAuthentication() middleware'i calistirildiktan sonra, kullanici
    login oldugunda, ASP.NET Core, kullanıcının kimliğini (User.Identity) olusturur ve HTTP istekleri
    boyunca bu bilgiyi tasır.
    User Nesnesi: User nesnesi, o anki oturumdaki kullaniciya ait bilgileri taşır. Kullanıcının oturum
    acip acmadigini (IsAuthenticated), kullanici adini ve diger kimlik bilgilerini icerir.
-->

@if(User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <li>
        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="Index"><i class="fa fa-solid fa-settings"></i> ADMIN</a>
    </li>
}

@if(User.Identity.IsAuthenticated)
{
    <li>
        <a  class="nav-link text-dark"
            aria-current="page"
            asp-area=""
            asp-controller="Account"
            asp-route-returnUrl ="@Context.Request.PathAndQuery()"
           asp-action="Logout"><i class="fa-solid fa-right-from-bracket"></i> Logout</a>
    </li>
}
else
{
    <li>
        <a class="nav-link text-dark"
           aria-current="page"
           asp-area=""
           asp-controller="Account"
           asp-route-returnUrl="@Context.Request.PathAndQuery()"
           asp-action="Login"><i class="fa-solid fa-left-from-bracket"></i> Login</a>
    </li>
}

BigStoreApp/Views/Shared/_Notification.cshtml
@if(TempData["info"] is not null)
{
    <div class="alert alert-info my-3" role="alert">
        @TempData["info"]
    </div>
}

@if (TempData["success"] is not null)
{
    <div class="alert alert-success my-3" role="alert">
        @TempData["success"]
    </div>
}

@if (TempData["danger"] is not null)
{
    <div class="alert alert-danger my-3" role="alert">
        @TempData["danger"]
    </div>
}